#!/bin/sh
REMOTEUSER=mwncampus
REMOTEHOST=xenon
DOMAIN=campus.masterweb.net
CAMPUSSRC=~/proj/mwn/campus
SPANELSRC=~/proj/spanel

rsync -e ssh -Pavz --del --delete-excluded --force --exclude '/.bzr' --exclude '*~' \
  $CAMPUSSRC $REMOTEUSER@$REMOTEHOST:
rsync -e ssh -Pavz \
  $SPANELSRC/lib/php/{sh_functions.inc.php,sh_translation.inc.php} \
  $SPANELSRC/lang \
  $REMOTEUSER@$REMOTEHOST:

ssh $REMOTEUSER@$REMOTEHOST campus/bin/campus-install \
  --branch prod \
  --source /home/$REMOTEUSER/campus \
  --target /s/$DOMAIN/www/ \
  --sh-functions-dir /home/$REMOTEUSER \
  install \
  $*
