#!/bin/sh
prefix=$HOME/catatharga

path=$prefix/rakitan/`date +"%Y-%m-%d@%H:%M:%S"`
mkdir -p "$path"; cd "$path"
wget http://rakitan.com -r -l1 -H -D rakitan.com -nH -A '/index.*,kategori.php*' -q --cache off

#path=$prefix/uc98/`date +"%Y%m%d%H%M%S"`
#mkdir -p $path; cd $path
#wget -q -nH -r -l1 -H -D www.uc98.com -e robots=off http://www.uc98.com/type.asp
