#!/bin/sh
prefix=$HOME/catatharga

path=$prefix/rakitan/`date +"%Y-%m-%d@%H:%M:%S"`
mkdir -p "$path"; cd "$path"
extract-links-from-file-or-url http://rakitan.com/ | \
  grep /kategori.php | \
  wget -q --cache off -i-

#path=$prefix/uc98/`date +"%Y%m%d%H%M%S"`
#mkdir -p $path; cd $path
#wget -q -nH -r -l1 -H -D www.uc98.com -e robots=off http://www.uc98.com/type.asp
