#!/bin/sh
rsync -e ssh -Pavz --del --delete-excluded --force --exclude '/.bzr' --exclude '/.git' --exclude '*~' \
  ~/proj/mwn/masterkey cdt@xenon:
rsync -e ssh -Pavz \
  ~/proj/spanel/lib/php/sh_functions.inc.php \
  ~/proj/spanel/lib/php/sh_translation.inc.php \
  ~/proj/spanel/lang \
  cdt@xenon:

ssh cdt@xenon masterkey/bin/masterkey-install \
  --site cdt \
  --branch cdtprod \
  --source /home/cdt/masterkey \
  --target /s/client.cyberdata.co.id/www/ \
  --sh-functions-dir /home/cdt \
  install \
  $*

ssh root@xenon \
'for p in /s/client.cyberdata.co.id/www/admin/mobile/sendsms; \
 do chown root.cdt "$p"; chmod 4755 "$p"; done; \
 rsync -Pav --del \
   --include "+ admin" \
   --include "+ admin/mobile" \
   --include "+ admin/mobile/**" \
   --include "+ includes" \
   --include "+ includes/mk-functions.php" \
   --include "+ includes/sh_functions.inc.php" \
   --include "+ includes/sh_translation.inc.php" \
   --include "- *" \
   /s/client.cyberdata.co.id/www/ /usr/local/cdtkey/;
 rsync -av /s/client.cyberdata.co.id/etc/configuration.php /usr/local/cdtkey/; # 2009-04-01 - 2 minggu lalu demi security gw memindahkan DOCROOT/configuration.php yg berisi password internet banking dll jadi symlink ke ../etc/.

'

