#!/usr/bin/perl -w

# udah gak memungkinkan lagi /backup/SERVER.local/ di-rsync secara
# keseluruhan, jumlah file/dir udah terlalu banyak, bisa >10jt file,
# proses rsync bisa >2GB ukurannya, server bisa tewas merangkak karena
# proses remote backup. maka dari itu harus displit. skrip ini
# mengambil tiap entri di bawah SERVER.local/ dengan rsync terpisah.

# XXX belum menghandle kasus entri yang sudah dihapus/tidak ada lagi
# di remote...

use strict;
use Log::Log4perl qw(:easy);
Log::Log4perl->easy_init($DEBUG);

my $PROGNAME = "do-remote-backup";

@ARGV == 2 or die "Usage: $PROGNAME <dir> <short-server-name>\n";
my ($dir, $shortsrvname) = @ARGV;

my $fullsrvname = $shortsrvname;
$fullsrvname .= ".masterwebnet.com" if $fullsrvname =~ /^server(\d+)/;

(-d $dir) or LOGEXIT "Dir $dir doesn't exist or not a dir";
(-d "$dir/remote-backups") or LOGEXIT "dir $dir/remote-backups doesn't exist or not a dir";
system "mkdir -p $dir/remote-backups/$shortsrvname";

my $sshopts = "-c arcfour -o StrictHostKeyChecking=no";

INFO "Remote backup for $shortsrvname started";

INFO "Retrieving first-level directories/entries ...";
my @ents = `ssh $sshopts root\@$fullsrvname "'ls'" -1 /backup/$shortsrvname.local/`;
chomp for @ents;

my $i = 0;
while ($i < @ents) {
    INFO "Running rsync /backup/$shortsrvname.local/$ents[$i] (".($i+1)."/".scalar(@ents).") ...";
    system qq(nice -n19 rsync -e "ssh $sshopts" ).
    qq(-rlptDHz --del --force ).
    qq(root\@$fullsrvname:'/backup/$shortsrvname.local/$ents[$i]' ).
    qq($dir/remote-backups/$shortsrvname/);
    $i++;
}

INFO "Remote backup for $shortsrvname ended";
