#!/bin/sh

FILE=configuration-mwn-unencoded.php
EFILE=configuration-mwn-encoded.php

set -x
[[ -f "$FILE" ]] || ( echo "ERROR: Please cd to directory where $FILE exists"; exit 1 )
scp "$FILE" root@23.masterweb.net:/opt/ioncube/
ssh root@23.masterweb.net /opt/ioncube/ioncube_encoder "$FILE" -o "/opt/ioncube/$EFILE"
scp root@23.masterweb.net:"/opt/ioncube/$EFILE" .


