#!/usr/bin/perl -w

use strict;
use LWP::Simple;

my @keywords = ("ulang tahun", "selamat ulang tahun", "ultah", "pesta ultah",
		"birthday", "birthday surprise", 
		"birthday cake", "birthday boy", "birthday girl", "birthday party");

my %bulan_long = (
    JANUARI  => 1,
    JANUARY  => 1,
    FEBRUARI => 2,
    FEBRUARY => 2,
    PEBRUARI => 2,
    MARET    => 3,
    MARCH    => 3,
    APRIL    => 4,
    MEI      => 5,
    MAY      => 5,
    JUNI      => 6,
    JUNE      => 6,
    JULI      => 7,
    JULY      => 7,
    AGUSTUS   => 8,
    AUGUST    => 8,
    SEPTEMBER => 9,
    OKTOBER   => 10,
    OCTOBER   => 10,
    NOVEMBER  => 11,
    NOPEMBER  => 11,
    DESEMBER  => 12,
    DECEMBER  => 12,
);

my $bulan_long_re = join( "|", map {quotemeta} keys %bulan_long );

my %bulan_short = (
    jan   => 1,
    feb   => 2,
    peb   => 2,
    mar   => 3,
    apr   => 4,
    mei   => 5,
    may   => 5,
    jun   => 6,
    jul   => 7,
    aug   => 8,
    agu   => 8,
    agt   => 8,
    agust => 8,
    sep   => 9,
    sept  => 9,
    okt   => 10,
    oct   => 10,
    nov   => 11,
    nop   => 11,
    dec   => 12,
    des   => 12,
);

my $URL = "https://kb.mwn.localdomain/internalwiki/Addressbook_Staf_MWN";
( $_ = get $URL) or die "FATAL: Can't get $URL: $!";
m#<span class="mw-headline">\s*birthdays by month\s*</span></h2>\s*(.+?)<a name="#s
    or die
    "FATAL: Can't find 'birthdays by month' section in Addressbook_Staf_MWN";

$_ = $1;
my $cur_month = 0;
for ( split /\015?\012/, $_ ) {
    m#^(?:<p>)?($bulan_long_re)#
        and do { $cur_month = $bulan_long{$1}; next };
    m#^</li></ul>$# and next;
    m#^</p>$#       and next;
    m#^<p><br />$#  and next;
    m#^$#           and next;

    my ( $name, $day, $bulan_short, $opts )
        = m#^(?:<ul><li>|</li><li>)\s*(.+?)\s+-\s+(\d+)(?:\s+(\w{3,5})\w*)\s*('[^']+'|"[^"]+")?$#
        or die "FATAL: Can't parse line: $_";
    $opts ||= qq!'{gi: {q: "${\( $keywords[rand @keywords] )}", day: 0}}'!;
    die "FATAL: Unknown bulan `$bulan_short' in line `$_'"
        unless $bulan_short{$bulan_short};
    my $bulan = $bulan_short ? $bulan_short{$bulan_short} : $cur_month;

    printf "BIRTHDAY %02d%02d1000 \"%s\" 0 %s\n", $day, $bulan, strip_tags($name), $opts;
}

sub strip_tags {
    local $_ = shift;
    s!<[^>]+>!!sg;
    $_;
}
