#!/usr/bin/perl -lw

use strict;
use Fatal;
use Storable;

chdir "/home/spanel-data";

print "#user;server;emails;plan;domains;expirydate";

my $u = retrieve "users.storable.cache";
for (keys %$u) {
  my $x = $u->{$_};
  next unless $x->{accountid};
  next if $x->{ismigrated} || $x->{ismigrating};
  my ($y,$m,$d) = $x->{expirydate} =~ /(\d{4})(\d{2})(\d{2})/;
  printf "%s;%s;%s;%s;%s;%04d-%02d-%02d\n", 
    $x->{_unixUser},
    $x->{_server},
    join(", ",@{$x->{clientemails}}),
    ($x->{plan} || $x->{package}),
    join(", ", @{$x->{domains}}),
    $y, $m, $d;
}
