#!/bin/bash
echo "# num keywords in site - mwn"
get-num-results-of-keyword-in-search-engine site:{id,kb,forums,blogs,www}.masterweb.net site:{masterwebnet.com,masterweb.net}
echo "# num pages in site - kompetitor"
get-num-results-of-keyword-in-search-engine site:{cbn.net.id,idwebhost.com,rumahweb.com,techscape.co.id,indoglobal.com,ardhosting.com,eazysmart.com}
echo "# num keywords - mwn"
get-num-results-of-keyword-in-search-engine mwn masterweb masterwebnet
echo "# num keywords - kompetitor"
get-num-results-of-keyword-in-search-engine idwebhost rumahweb techscape ardhosting eazysmart
# XXX rank website mwn utk keyword 'hosting', 'perusahaan hosting', ... (search bahasa indo)
