#!/usr/bin/perl

use FindBin '$Bin';
use POSIX qw(strftime);

my @urls = map { "http://www.bapepam.go.id/reksadana/smallMain.asp?typ=$_->[0]&opt=$_->[1]" }
  ([1 => tetap], [2 => saham], [3 => campur], [4 => uang], [5 => proteksi], [7 => indeks]);

my $dir = sprintf( "%s/../rd/%s", $Bin, ( strftime "%Y-%m-%d", localtime ) );
system qq(mkdir -p "$dir");
chdir $dir;

for (@urls) {
    chomp;
    system qq(wget -q "$_");
}
