#!/usr/bin/perl

use 5.010;
use strict;
use warnings;

use POSIX;

my %logs; # key="username-YYYY-MM-DD", val=>$ip

#for my $f ("zcat /var/log/squid/access*z |") {
for my $f (map { "/var/log/squid/$_" } "access.log", "access.log.1") {
    open my ($fh), $f or do { warn "Can't open $f: $!"; next };
    while (<$fh>) {
        next unless my ($time, $ip, $username) =
            /^
             (\S+) \s+ # time
             \d+ \s+
             (\S+) \s+ # ip
             TCP_MISS\S+ \s+
             \d+ \s
             CONNECT \s
             forum\.mwn\.localdomain:443 \s
             (\w+) # username
            /x;
        my $date = POSIX::strftime("%Y-%m-%d", gmtime($1+7*3600));
        $logs{"$username $date"} = $ip;
    }
}

#use Data::Dump; dd \%logs;

for my $k (sort keys %logs) {
    say $k, " ", $logs{$k};
}
