#!/bin/sh
rsync -e ssh -Pavz --del --delete-excluded --force --exclude '/.bzr' --exclude '/.git' --exclude '*~' \
  ~/proj/mwn/masterkey mwnwhmcs@xenon:
rsync -e ssh -Pavz \
  ~/proj/spanel/lib/php/{sh_functions.inc.php,sh_translation.inc.php} \
  ~/proj/spanel/lang \
  mwnwhmcs@xenon:

ssh mwnwhmcs@xenon masterkey/bin/masterkey-install \
  --site mwn \
  --branch test \
  --source /home/mwnwhmcs/masterkey \
  --target /s/test.whmcs.mwn.localdomain/www/ \
  --sh-functions-dir /home/mwnwhmcs \
  install \
  $*
