#!/bin/sh
rsync -e ssh -Pavz --del --delete-excluded --force --exclude '/.bzr' --exclude '/.git' --exclude '*~' \
  ~/proj/mwn/masterkey mwnwhmcs@xenon:
rsync -e ssh -Pavz \
  ~/repos/php-sh_functions/sh_functions.inc.php \
  ~/repos/php-sh_functions/sh_translationutils.inc.php \
  ~/repos/php-sh_functions/sh_utils.inc.php \
  ~/repos/php-sh_functions/sh_grid.inc.php \
  ~/repos/php-sh_functions/sh_activerecord.inc.php \
  ~/repos/spanel/lang \
  mwnwhmcs@xenon:

ssh mwnwhmcs@xenon masterkey/bin/masterkey-install \
  --site mwn \
  --branch test \
  --source /home/mwnwhmcs/masterkey \
  --target /s/test.whmcs.mwn.localdomain/www/ \
  --sh-functions-dir /home/mwnwhmcs \
  install \
  $*
