#!/bin/sh
rsync -e ssh -Pavz --del --delete-excluded --force --exclude '/.bzr' --exclude '*~' \
  ~/proj/mwn/masterkey mwnwhmcs@xenon:
rsync -e ssh -Pavz \
  ~/proj/spanel/lib/php/sh_functions.inc.php mwnwhmcs@xenon:

ssh mwnwhmcs@xenon masterkey/bin/masterkey-install \
  --branch prod \
  --source /home/mwnwhmcs/masterkey \
  --target /s/masterkey.masterweb.net/www/ \
  --sh-functions-path /home/mwnwhmcs/sh_functions.inc.php \
  install \
  $*

ssh root@xenon \
'for p in /s/masterkey.masterweb.net/www/admin/mobile/sendsms; \
 do chown root.mwnwhmcs "$p"; chmod 4755 "$p"; done; \
 rsync -Pav --del \
   --include "+ admin" \
   --include "+ admin/mobile" \
   --include "+ admin/mobile/**" \
   --include "+ configuration.php" \
   --include "+ includes" \
   --include "+ includes/mk-functions.php" \
   --include "- *" \
   /s/masterkey.masterweb.net/www/ /usr/local/masterkey/
'
