#!/bin/sh
rsync -e ssh -Pavz --del --delete-excluded --force --exclude '/.bzr' --exclude '*~' \
  ~/proj/mwn/masterkey mwnwhmcs@xenon:
rsync -e ssh -Pavz \
  ~/proj/spanel/lib/php/sh_functions.inc.php \
  ~/proj/spanel/lib/php/sh_translation.inc.php \
  ~/proj/spanel/lang \
  mwnwhmcs@xenon:

ssh mwnwhmcs@xenon masterkey/bin/masterkey-install \
  --branch prod \
  --source /home/mwnwhmcs/masterkey \
  --target /s/masterkey.masterweb.net/www/ \
  --sh-functions-dir /home/mwnwhmcs \
  install \
  $*

ssh root@xenon \
'for p in /s/masterkey.masterweb.net/www/admin/mobile/sendsms; \
 do chown root.mwnwhmcs "$p"; chmod 4755 "$p"; done; \
 rsync -Pav --del \
   --include "+ admin" \
   --include "+ admin/mobile" \
   --include "+ admin/mobile/**" \
   --include "+ includes" \
   --include "+ includes/mk-functions.php" \
   --include "+ includes/sh_functions.inc.php" \
   --include "+ includes/sh_translation.inc.php" \
   --include "- *" \
   /s/masterkey.masterweb.net/www/ /usr/local/masterkey/;
 rsync -av /s/masterkey.masterweb.net/etc/configuration.php /usr/local/masterkey/; # 2009-04-01 - 2 minggu lalu demi security gw memindahkan DOCROOT/configuration.php yg berisi password internet banking dll jadi symlink ke ../etc/.
   
'

