#!/usr/bin/perl -w

use strict;
use Cwd;
use Log::Log4perl qw(:easy);
use File::Slurp;
use File::Temp qw/tempfile/;
use App::Options (
    option => {
        tag => { type => 'string', required => 0, default => '' },
    },
);

my @files;

Log::Log4perl->easy_init($DEBUG);

# cek argumen
unless (@ARGV) {
  print "Usage: $0 [--tag=some_label] <moviedir> ...\n";
  exit 1;
}

my $orig_dir = getcwd;

for my $dir (@ARGV) {
  chdir $orig_dir;

  chdir $dir or do {
    WARN "Can't chdir to `$dir', skipped";
    next;
  };

  my $msg = `make-phpbb-movie-posting`;
  length($msg) or do {
    WARN "Can't get movie posting information for dir `$dir', skipped";
    next;
  };

  # some extra tags from imdb
  my $tags = $App::options{tag} ? "[$App::options{tag}] " : "";

  if (-f "imdb.html") {
    local $_ = read_file("imdb.html");
    my @genres = map {lc} ($_ =~ m{<a href="/Sections/Genres/([^/]+)/">}g);
    if ($genres[1]) { $tags .= "[$genres[0]/$genres[1]] " }
    elsif ($genres[0]) { $tags .= "[$genres[0]] " }
    my @langs = map {lc} ($_ =~ m{<a href="/Sections/Languages/([^/]+)/">}g);
    if (@langs) {
      if ($langs[0] eq 'cantonese') { $tags .= "[zh-c] " }
      elsif ($langs[0] eq 'english') { $tags .= "[en] " }
      elsif ($langs[0] eq 'french') { $tags .= "[fr] " }
      elsif ($langs[0] eq 'german') { $tags .= "[de] " }
      elsif ($langs[0] =~ /chinese|mandarin/) { $tags .= "[zh-m] " }
      elsif ($langs[0] =~ /bahasa|indonesian?/) { $tags .= "[id] " }
      elsif ($langs[0] =~ /japanese/) { $tags .= "[jp] " }
      elsif ($langs[0] =~ /korean/) { $tags .= "[ko] " }
    }
  }

  my ($fh, $filename) = tempfile();
  print $fh "Subject: $tags$dir\n";
  print $fh "\n";
  print $fh $msg;
  push @files, $filename;
}

# send it!
system "phpbb2-post --profile=sharing_movie ".join(" ", @files);
unlink @files;

