#!/usr/bin/perl

use strict;
use lib '/c/lib/perl'; # XXX hardcoded
use Spanel::Utils;
#use Data::Dumper;
use Getopt::Long;
use List::Util qw(shuffle);

use vars qw($SPANEL_SERVERS $CPANEL_SERVERS $PLESK_SERVERS);

my $verbose = 0;
GetOptions('--verbose' => \$verbose);

load_servers_config();
my @servers = grep {
    !in_('intranet', $_->{config}{tags}) &&
    !in_('NOT-YET', $_->{config}{tags}) }
    values %$SPANEL_SERVERS, values %$CPANEL_SERVERS, values %$PLESK_SERVERS;

my @hosts = map { $_->{config}{local}{hostname} } @servers;

push @hosts, qw(id.masterweb.net us.masterweb.net masterweb.net);

# 1/3-nya aja secara random, karena begitu direquest maka oleh
# netcraft akan diremember beberapa hari
@hosts = shuffle @hosts;
for (0..($#hosts/3)) {
    my $host = $hosts[$_];
    print "[", (scalar localtime), "] $host\n" if $verbose;
    system "wget -q http://uptime.netcraft.com/up/graph?site=$host";
}
