#!/bin/bash

ssh antimwnwhmcs@radon 'DEBUG=1 ~/mkey/app/bin/set-invoice-sale-date; cd ~/mkey/app/bin; perl -I../lib/perl -MMasterkey::AdminArea -e'\''\'"''"' Masterkey::AdminArea::login(); $Masterkey::AdminArea::mech->get("$Masterkey::Config::conf->{site_url}/admin/fa-sales-journal.php?output_format=txtsummary1"); print $Masterkey::AdminArea::mech->content'\''\' | \
  perl -MNumber::Format -MDateTime -MCalendar::ID::Holiday=count_id_workdays -ne'
    BEGIN {
        $now = DateTime->now;
        $eom = $now->clone; $eom->set_day(1); $eom->add(months=>1); $eom->subtract(days=>1);
        $som = $now->clone; $som->set_day(1);
        $fmt = Number::Format->new;
    }
    if (my ($rp, $sen) = /^\s+Total PENDAPATAN\s+IDR\s+([0-9.]+),(\d\d) C/) {
        $rp =~ s/\D//g;
        $rp += $sen/100.0;
        print;

        # calendar days
        #printf "    --> Perkiraan hingga akhir bulan: %s (sisa hari=%d)\n",
        #    $fmt->format_number($rp * $eom->day/$now->day), ($eom->day-$now->day);

        # work days
        my $res;
        $res = Calendar::ID::Holiday::count_id_workdays(start_date=>$som, end_date=>$eom);
        die "count_id_workdays failed (1): $res->[0] - $res->[1]" unless $res->[0] == 200;
        $bd_this_mon = $res->[2];
        $res = Calendar::ID::Holiday::count_id_workdays(start_date=>$som, end_date=>$now);
        die "count_id_workdays failed (2): $res->[0] - $res->[1]" unless $res->[0] == 200;
        $bd_so_far   = $res->[2];
        if ($bd_so_far) {
            printf "    --> Perkiraan hingga akhir bulan: %s (total hari kerja=%d, hingga hari ini=%d, sisa=%d)\n",
                $fmt->format_number($rp * $bd_this_mon/$bd_so_far), $bd_this_mon, $bd_so_far, ($bd_this_mon - $bd_so_far);
        }

    } else {
        print;
    }
    '

# XXX seharusnya berdasarkan hari kerja agar lebih akurat: (total jum hari kerja
# sen-jum ) / (jumlah hari kerja sen-jum yang sudah dilewati hingga hari ini)

