#!/bin/bash
ssh mwnwhmcs@xenon 'cd wwwbin && perl -I. -MMasterkey::Utils -e'\''\'"''"'init_(); mkey_login(); $Mech_Mkey->get("$Masterkey::Config->{CONFIG_ADMIN_URL}/fa-sales-journal.php?period=2010-12&output_format=txtsummary1"); print $Mech_Mkey->content'\''\' | \
  perl -MNumber::Format -MDateTime -MDateTime::BusinessHours -ne'
    BEGIN {
        $now = DateTime->now;
        $eom = $now->clone; $eom->set_day(1); $eom->add(months=>1); $eom->subtract(days=>1);
        $som = $now->clone; $som->set_day(1);
        $fmt = Number::Format->new;
    }
    if (my ($rp, $sen) = /^\s+Total PENDAPATAN\s+IDR\s+([0-9.]+),(\d\d) C/) {
        $rp =~ s/\D//g;
        $rp += $sen/100.0;
        print;

        # calendar days
        #printf "    --> Perkiraan hingga akhir bulan: %s (sisa hari=%d)\n",
        #    $fmt->format_number($rp * $eom->day/$now->day), ($eom->day-$now->day);

        # business days & hours
        $bt = DateTime::BusinessHours->new(datetime1=>$som, datetime2=>$eom);
        $bs = DateTime::BusinessHours->new(datetime1=>$som, datetime2=>$now);
        $bd_this_mon = $bt->getdays  + 1;
        $bd_so_far   = $bs->getdays  + 1;
        $bh_this_mon = $bt->gethours + 1;
        $bh_so_far   = $bs->gethours + 1;
        if ($bh_so_far) {
            printf "    --> Perkiraan hingga akhir bulan: %s (total hari/jam kerja=%d/%d, hingga hari ini=%d/%d, sisa=%d/%d)\n",
                $fmt->format_number($rp * $bh_this_mon/$bh_so_far),
                $bd_this_mon, $bh_this_mon,
                $bd_so_far, $bh_so_far,
                ($bd_this_mon - $bd_so_far), ($bh_this_mon - $bh_so_far);
        }

    } else {
        print;
    }
    '

# XXX seharusnya berdasarkan hari kerja agar lebih akurat: (total jum hari kerja
# sen-jum ) / (jumlah hari kerja sen-jum yang sudah dilewati hingga hari ini)

