#!/bin/sh

# ganti jika source mwn gak mirip dg yg di sini
cd /home/steven/proj/mwn/spanel-configs

# owner jangan dipreserve :)

/c/sbin/spanel-multissh $@ --rsync --nouse-ip --user root -- \
  -rlptD -Pvz --del --exclude '.svn' --exclude '*~' \
  \
  mail-templates \
  newaccount-templates \
  default-dns-zone.yaml \
  dns-zone-templates \
  www \
  www-templates \
  plans.yaml \
  servers/'[[SERVERID]]'/spanel.yaml \
  \
  '[[USER]]@[[IP_OR_HOSTNAME]]':/etc/spanel/
