#!/bin/sh
rsync --exclude '.git' --exclude '*.counter' --exclude '*.rrd' --exclude '*~' --exclude 'tmp/*' --exclude 'www/tmp/*' --exclude '*.psd' --delete \
-e ssh -Pavz $* mwn@32.masterwebnet.com:/s/us.masterwebnet.com/www/ $HOME/repos/mwn-site/
