#!/bin/sh

rsync --del -e ssh -Pavz $* \
  --exclude '*~' --exclude '.svn' \
  --exclude '/config.php' \
  --exclude '/images/avatars/' \
  $HOME/proj/mwn/foruminternal/ \
  mwn@forum.mwn.localdomain:sites/forum.mwn.localdomain/ssl/
