#!/bin/sh

SOURCE=/home/steven/proj/mwn/spanel-configs/servers

# note: -rlptD = -a minus -og (owner, group)

/c/sbin/spanel-multissh --rsync --user root --none --server server23 --server ciledug -- --exclude '*~' --delete-excluded -rlptD -Pvz --del $SOURCE/* '[[USER]]@[[IP]]':/etc/spanel/servers/
/c/sbin/spanel-multissh --rsync --user root --all --has mwn --has dns --lack intranet -- --exclude '*~' --delete-excluded -rlptD -Pvz --del $SOURCE/* '[[USER]]@[[IP]]':/etc/spanel/servers/
