#!/bin/bash
src=$HOME/proj/mwn/dns/zone=masterweb.net
ssh=root@server42213d.masterweb.net
path=/u/masterw/sysetc

# karena ketiga file ini hardlink satu sama lain, gak perlu, cukup kopikan 1 aja
#for f in zone={masterweb.net,masterwebnet.com,mwn.co.id,masterweb.co}; do
#  scp $src $h:$p/$f
#done
scp $src $ssh:$path/

# sekalian sync dns
ssh $ssh /c/sbin/sync-domains-to-dns-servers --debug

