#!/bin/sh

set -x

TMPDIR=/tmp/kbriv
TARGETHOST=h14763@kbrivientiane.org
#if [ $0 == "prod" ]; then TARGETVHOST=kbrivientiane.org; else TARGETVHOST=staging.kbrivientiane.org; fi
TARGETVHOST=kbrivientiane.org

rsync -az --exclude '/.bzr'  --exclude '/.git' --exclude '*~' --del --force ~/proj/webdev/kaishi/              $TMPDIR/
rsync -az --exclude '/.bzr'  --exclude '/.git' --exclude '*~'               ~/proj/spanel/lib/php/sh_*.inc.php $TMPDIR/
rsync -az --exclude '/.bzr'  --exclude '/.git' --exclude '*~'               ~/proj/webdev/kbri-vientiane/      $TMPDIR/
rsync -e ssh -Pavz  --exclude '/.bzr' --exclude '/.git' --exclude '*~' --exclude '*.t.*' \
  --exclude '/config.inc.php' \
  --exclude '/upload' \
  --exclude '/banners' \
  --exclude '/data' \
  $* $TMPDIR/ $TARGETHOST:/s/$TARGETVHOST/www/
