#!/bin/sh
TARGETHOST=t73214@mybabytree.org
TARGETDIR=mbt-gdocs

rsync -e ssh -Pavz --del --force --exclude '/.bzr' --exclude '/.git' --exclude '*~' \
  --exclude '/config.inc.php' \
  --exclude '/log' \
  --exclude '/logs/*' \
  --exclude '/data/*' \
  --exclude '/mbt.db' \
  --exclude '/mbt.db' \
  --exclude '/tmp' \
  ~/proj/webdev/mbt-gdocs/ $TARGETHOST:$TARGETDIR

rsync -e ssh -Pavz \
  ~/proj/spanel/lib/php/sh_*.inc.php $TARGETHOST:$TARGETDIR

