#!/usr/bin/perl

use FindBin '$Bin';
use lib $Bin;
BEGIN { require 'common.pl'; }

$TO='/backup/archive/mirrors';
$EXCLUDES=['*.tmp'];

$PROTO="rsync+ssh"; $USER='archive'; $HOST="32.masterwebnet.com"; $DIR="mirrors"; $RATE_LIMIT=75;

Mirror();
