#!/usr/bin/perl

use FindBin '$Bin';
use lib $Bin;
BEGIN { require 'common.pl'; }

$TO='/backup/archive/mirrors/cpan';
$EXCLUDES = [];

#$PROTO='rsync'; $HOST='mirrors.kernel.org'; $DIR='mirrors/CPAN'; $RATE_LIMIT=30;
#$PROTO='ftp'; $HOST='mirrors.kernel.org'; $DIR='cpan'; $RATE_LIMIT=30; # lebih parah dari rsync-nya, ditolaknya cepet..

$PROTO='rsync'; $HOST='rsync.secsup.org'; $DIR='perl'; $RATE_LIMIT=60;

Mirror();
