#!/usr/bin/perl

use FindBin '$Bin';
use lib $Bin;
BEGIN { require 'common.pl'; }

$TO='/backup/archive/mirrors/debian';
$EXCLUDES = [excludes_debian_arch_not_i386()];

#$PROTO="rsync"; $HOST='mirrors.kernel.org'; $DIR='mirrors/debian'; $RATE_LIMIT=30;
$PROTO="rsync"; $HOST='rsync.secsup.org'; $DIR='debian'; $RATE_LIMIT=100;

MirrorDebian();

