#!/usr/bin/perl

use FindBin '$Bin';
use lib $Bin;
BEGIN { require 'common.pl'; }

$TO='/u/archive/public/mirrors/fedora';
$EXCLUDES = [
	     # unwanted archs (all but i386)
	     'ppc', 'x86_64', 

	     'SRPMS/*',

             # old versions
             '/1', '/2', '/3', '/4',

             # debug rpms
             'debug/*',

             # iso images
             'iso/*',
            ];

$PROTO='ftp'; $HOST='fedora.cbn.net.id'; $DIR='/pub/Fedora'; $RATE_LIMIT = 50;

Mirror();

__END__

# stats

# 2006-11-30: dari cbn, fedora 5 & 6 + extras... + source - iso, hanya
# i386 = 31GB. tanpa source = 10GB.

