#!/usr/bin/perl

use FindBin '$Bin';
use lib $Bin;
BEGIN { require 'common.pl'; }

$TO='/backup/archive/mirrors/debian';
$EXCLUDES = [excludes_debian_arch_not_i386()];

# 2006-11-18
$PROTO="rsync"; $HOST='mirrors.kernel.org'; $DIR='mirrors/ubuntu'; $RATE_LIMIT=30;

MirrorDebian();
