#!/usr/bin/perl -w
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, make this file executable.

use strict;
use File::Slurp;

my $counter_path = "/media/bismuthb/home/sloki/user/steven/public/git/mwn-last-rev-posted-to-forum.txt";
my $counter = read_file($counter_path) or die "Can't read counter file or counter not initialized: $counter_path";
chomp($counter);

my @revs;
for (`git log $counter..HEAD --pretty=oneline --reverse`) {
    /^(\w+) .+/ or die "Weird line in git log output: $_";
    push @revs, $1;
}

my $fail = 0;
for (@revs) {
    print "Posting rev $_ ke forum ...\n";
    system "( echo 'Subject: commit message'; echo; echo -n '[code]'; git log -1 -p $_; echo '[/code]' ) | phpbb2-post --profile=commit_mwn --bbcode=1 -";
    if ($?) {
        warn "Gagal post (exit=$?), aborting ...";
        $fail++;
        last;
    }
    unless ($fail) {
        write_file($counter_path, $revs[-1]);
    }
}
