#!/usr/bin/perl -w

use strict;
use List::Util qw/shuffle/;
use Proc::PID::File;
use App::Options (
    option => {
        rsync_opts => {
            description => "Extra rsync options, will be passed to 'backup-with-history' script",
            type        => "string",
            default     => "",
            required    => 0,
        },
        bin_path => {
            description => "Path to 'backup-with-history' script",
            type        => "string",
            default     => "",
            required    => 0,
        },
        hist_levels => {
            description => "A comma-separated list of numbers to specify the history levels, will be passed to 'backup-with-history' script",
            type        => "string",
            default     => "-7,4,3",
            required    => 0,
        },
        user => {
            description => "User",
            type        => "string",
            required    => 1,
            default     => "root",
        },
        host => {
            description => "Host",
            type        => "string",
            required    => 1,
        },
        ssh_port => {
            description => "ssh port",
            type        => "int",
            required    => 1,
            default     => 22,
        },
        dir => {
            description => "Backup directory",
            type        => "string",
            required    => 1,
            default     => "/backup/cpbackup",
        },
    }
);
use Log::Log4perl qw(:easy);

# --- subs

sub esc {
    local $_ = shift;
    s/'/'"'"'/g;
    "'$_'";
}

# --- main

@ARGV == 1 or die "Usage: $0 <dest>\n";
my ( $dst0 ) = @ARGV;
for ( $dst0 ) {s!/$!!}

Log::Log4perl->easy_init($DEBUG);

my $name = $App::options{host};
$name =~ s/[^A-Za-z0-9]+/_/g;
LOGDIE "Remote backup to cPanel server $App::options{host} already running, aborting"
    if Proc::PID::File->running(name=>$name);

INFO "Remote backup for cPanel server $App::options{host} started";

INFO "Listing files to backup ...";
my $sshopts = "-p $App::options{ssh_port} -c arcfour -o StrictHostKeyChecking=no";
my $dir0 = $App::options{dir};

my $bin = ($App::options{bin_path} ? "$App::options{bin_path}/" : "") . "backup-with-history";
my $cmd = "$bin " .
    ($App::options{hist_levels} ? "--hist_levels=".esc($App::options{hist_levels})." " : "").
    ($App::options{rsync_opts} ? "--rsync_opts=".esc($App::options{rsync_opts})." " : "").
    esc("$App::options{user}\@$App::options{host}:$App::options{dir}/daily") . " ".
    esc("$dst0");
INFO "Running backup for dir=$App::options{dir}/daily ...";
DEBUG "cmd: $cmd";
system $cmd;

INFO "Remote backup for cPanel server $App::options{host} ended";
