#!/usr/bin/perl

use bytes;

sub c_escapechar($) {
  my $c = $_[0];
  my $o = ord($c);

  if ($o == 0) { "\\0" }
  elsif ($o == 0x0d) { "\\r" }
  elsif ($o == 0x0a) { "\\n" }
  elsif ($o == 0x09) { "\\t" }
  else { sprintf("\\x%02x", $o) }
}

sub c_escape($) {
  local $_ = shift;

  s/([\x00-\x1f\x80-\xff])/c_escapechar($1)/eg;
  $_;
}

while (<>) {
  chomp;
  print c_escape($_),"\n";
}
