#!/usr/bin/perl

# "dzil build" creates build directory and tarballas in the project root dir.
# this clutters things. run this to clean the build files.

use 5.010;
use strict;
#use warnings;

use Log::Any::App '$log';
use String::ShellQuote;

BEGIN { $::Log_Level = 'info' }

# very simple implementation, assume normal dist name like Foo-Bar-0.01. more
# proper implementation should read dist.ini

for (<*>) {
    $log->trace("Processing $_ ...");
    next unless /^[A-Z]\w+(-[A-Za-z]\w+)+-[0-9.]+(\.tar\.gz)?$/;
    $log->info("Deleting $_ ...");
    next if $ENV{DRY} || $ENV{DRYRUN} || $ENV{DRY_RUN};
    system "rm -rf ".shell_quote($_);
}
