# generated by mkexr.rb

EXERB  = exerb
OUTPUT = clean_redlof.exe
INPUT  = clean_redlof.exr
FILES  = clean_redlof.rb c:/ruby/lib/ruby/1.8/find.rb

all: $(OUTPUT)

$(OUTPUT): $(INPUT) $(FILES)
	$(EXERB) $(INPUT)
	chmod +x $(OUTPUT)

go: all
	$(OUTPUT)

clean:
	rm $(OUTPUT)
