#!/usr/bin/perl -l

use strict;
use Getopt::Long;

my %Opt = (
        samprate => 44100,
        bitrate => '128k',
       );
my %DefOpt = %Opt;

GetOptions(
           'help' => \$Opt{help},
           'bitrate=s' => \$Opt{bitrate},
           'samprate=i' => \$Opt{samprate},
          );
if ($Opt{help}) {
  print <<EOF;
$0 [options]

Options:
 --help       Show this message and exit.
 --bitrate=B  Set bitrate in bit/s, default is $DefOpt{bitrate}.
 --samprate=B Set sampling rate in Hz, default is 44100.
EOF
  exit 0;
}

my @files;
if (@ARGV) {
    @files = @ARGV;
} else {
    @files = (<*.mp3>);
}

for my $f (@files) {
  if (-f "$f.ogg") {
    print "WARNING: $f.ogg exists, skipped";
  }
  my $esc = esc($f);
  my $cmd = "ffmpeg -i $esc -ar $Opt{samprate} -ab $Opt{bitrate} $esc.ogg";
  print $cmd;
  system $cmd;
}

sub esc {
  local $_ = shift;
  s/'/'"'"'/g;
  "'$_'";
}
