#!/usr/bin/perl

# created: 2011-06-14

use 5.010;
use strict;
use warnings;

use JSON;
use LWP::Simple;

my $json = JSON->new->allow_nonref;

die "Usage: $0 <CPANID> ...\n" unless @ARGV;

binmode STDOUT, ":utf8";

for my $cpanid (@ARGV) {
    my $res = get "http://api.metacpan.org/v0/release/_search?q=author:".
        uc($cpanid)."%20AND%20status:latest&fields=name&size=5000";
    $res = $json->decode($res);
    die "MetaCPAN timed out" if $res->{timed_out};
    my @dists;
    for my $hit (@{ $res->{hits}{hits} }) {
        my $dist = $hit->{fields}{name};
        $dist =~ s/-\d.+//;
        push @dists, $dist;
    }

    printf "%s has %d distributions on CPAN\n", $cpanid, scalar(@dists);
}
