#!/usr/bin/perl -w

use strict;
use File::Find;

sub sub1 {
    return unless -f $_;

    my $delete = 0;

    # nama file
    $delete++ if /^(desktop\.ini|thumbs\.db|.+demonoid.*\.txt)$/i;

    # ext
    $delete++ if /\.(url|nfo|m3u|sfv)$/i;

    return unless $delete;

    print "$File::Find::dir/$_\n";
    unlink $_;
}

find(\&sub1, ".");
