#!/bin/sh

SBINDIR=$HOME/proj/spanel/sbin

SRC=$HOME/repo/spanel
# default is home directory
TARGET=

echo "Updating source trees (~/spanel on remote servers) ..."
$SBINDIR/spanel-multissh $@ --nouse-ip --rsync --user root -- \
  -Pavz --del --force --exclude '.svn' --exclude '.bzr' --exclude '.git' --exclude '*~' \
  "$SRC" '[[USER]]@[[IP_OR_HOSTNAME]]':$TARGET

echo "Running spanel-install on remote servers ..."
$SBINDIR/spanel-multissh $@ --nouse-ip --user root -- spanel/sbin/spanel-install --nocheck install

# XXX not yet: optional: run spanel-setup
