#!/usr/bin/perl

# if given a url, then download it to imdb.url and imdb.html. else, find
# imdb.url and download that url to imdb.html.

if (@ARGV and $ARGV[0] =~ m#^http://#) {
    open F, ">imdb.url";
    print F $ARGV[0];
    close F;
}

exit unless -f "imdb.url";
system "wget -q -O imdb.html -i imdb.url";

