#!/usr/bin/perl

# 990928, pas waktu mo nge-print manual PostgreSQL
# 000710, nambah biar bisa get document dari URL. BASE HREF aware.
# 2011-06-17, moved to SHARYANTO::HTML::Extract::ImageLinks

die "temporarily not working yet, ".
    "please use SHARYANTO::HTML::Extract::ImageLinks\n";

use Sub::Spec::CmdLine qw(run);
run(module=>'SHARYANTO::HTML::Extract::ImageLinks', sub=>'extract_image_links');
