#!/usr/bin/perl

use 5.010;
use strict;
use warnings;

use Perinci::CmdLine::Easy qw(run_cmdline_app);

run_cmdline_app(
    sub => sub {
        my $uuid = shift or die "Please specify uuid";

        $uuid = lc($uuid);
        $uuid =~ s/[^0-9a-f]+//g;

        die "Invalid uuid, not 32 chars long: $uuid" unless length($uuid) == 32;

        $uuid =~ s/(.{8})(.{4})(.{4})(.{4})(.{12})/$1-$2-$3-$4-$5/;
        $uuid;
    },
    summary => 'Change 1dde05aea2624c69a12db461afb00a6b to 1dde05ae-a262-4c69-a12d-b461afb00a6b',
    argv => ['uuid*'],
);
