#!/usr/bin/ruby

# 2005-11-03

require 'yaml'

storages = YAML::load(File::open('/home/steven/storage_media_list.yaml').read)
summary = {}

storages.each_pair {|name, storage|
  #next if storage['current_status'] != 'OK'
  next if %w(REPLACED).include? storage['current_status']

  if storage['filesystem'] =~ /^(?:bc|bestcrypt)\+(.+)/
    encrypted = true
    encryption_type = "bc"
    filesystem = $1
  elsif storage['filesystem'] =~ /^(dm|dm-?crypt)\+(.+)/
    encrypted = true
    encryption_type = "dm"
    filesystem = $1
  else
    encrypted = false
    encryption_type = nil
    filesystem = storage['filesystem']
  end
  summary[name] = {
    'type' => storage['type'],
    'subtype' => storage['subtype'],
    'serial_number' => storage['serial_number'],
    'mount_point' => storage['mount_point'],
    'index_point' => storage['index_point'],
    'filesystem' => filesystem,
    'encrypted' => encrypted,
    'encryption_type' => encryption_type,
    'dont_index' => (storage['dont_index'] ? true : false),
  }
}

f = File::open('/u/steven/private/etc/storage_media_summary.yaml', 'w') 
f.puts "# Generated by #{$0} on #{Time.now}"
f.puts
f.puts summary.to_yaml

