#!/usr/bin/perl

$cmd = "";
for (@ARGV) {
    if (!length($cmd)) { $cmd = "grep -i '$_' ~/notes/todl.txt ~/notes/done-dl.txt ~/notes/done-deleted-dl.txt" }
    else { $cmd .= " | grep -i '$_'"; }
}

print "# $cmd\n";
system $cmd;

