#!/usr/bin/perl

use Test::Harness;

BEGIN {
    (-d "t") or die "Can't find t/ subdir here\n";
    (-d "lib") or die "Can't find lib/ subdir here\n";
}

use lib "lib";
my @files;
if (@ARGV) {
    @files = @ARGV;
} else {
    @files = glob "t/*.t";
}
runtests(@files);

