#!/usr/bin/perl

use 5.010;
use strict;
use warnings;

use Data::Format::Pretty::Console qw(format_pretty);
use YAML::Syck;

my $yaml = join "", <>;
my $data = Load($yaml);
$data = $data->[2]{stmt}{transactions};
print format_pretty(
    $data,
    {interactive => 1,
     table_column_orders => [[qw/date seq description amount/]]}
);
