#!/usr/bin/perl

use 5.010;
use strict;
use warnings;

use Data::Format::Pretty::Console qw(format_pretty);
use YAML::Syck;

my $yaml = join "", <>;
my $data = Load($yaml);

# strip envelope
if (ref($data) eq 'ARRAY' && $data->[0]+0 == 200) {
    $data = $data->[2];
}

print format_pretty(
    $data->{transactions},
    {interactive => 1,
     table_column_orders => [[qw/date seq description amount/]]}
);
