#!/usr/bin/perl

use 5.010;
use strict;
use warnings;

use Data::Format::Pretty::Console qw(format_pretty);
use YAML::Syck;

my $yaml = join "", <>;
my $data = Load($yaml);
print format_pretty(
    $data,
    {table_column_orders=>[[qw/date seq description amount/]]}
);



