#!/bin/bash

# damn you php, i want my dl()

php -d 'extension=yaml.so' -r'
if (count($argv) > 2) die("Usage: $argv[0] < \n");
$ini = file_get_contents(count($argv) > 1 ? $argv[1] : "php://stdin");
$data = parse_ini_string($ini, true);
echo yaml_emit($data);' "$*"
