#!/usr/bin/perl
$wget = (-x "/usr/bin/wget2") ? "/usr/bin/wget2" : "wget"; # support utk yg wget-nya diblokir
$_ = `$wget -q -O- --no-cache 'http://www.klikbca.com'`;
m!<td[^>]+"/images/kurs-tanggal.jpg">&nbsp;&nbsp;(\d\d+)-(\w{2,6})-(\d\d\d\d)\s*/\s*(\d\d?):(\d\d?) WIB(.+?)"/images/kurs-bawah.jpg"!s or
    die "Gagal memparsing kurs\n";
$waktu = "$1-$2-$3 $4:$5 WIB";
$kurs = $6;
$kurs =~ m!>USD<.+?>(\d+\.\d+)<.+?>(\d+\.\d+)<!s or die "Gagal memparsing kurs USD\n";
($usd_jual, $usd_beli) = ($1, $2);
#$kurs =~ m!>SGD<.+?>(\d+\.\d+)<.+?>(\d+\.\d+)<!s or die "Gagal memparsing kurs SGD\n";
#($sgd_jual, $sgd_beli) = ($1, $2);
#$kurs =~ m!>HKD<.+?>(\d+\.\d+)<.+?>(\d+\.\d+)<!s or die "Gagal memparsing kurs HKD\n";
#($hkd_jual, $hkd_beli) = ($1, $2);
#$kurs =~ m!>CHF<.+?>(\d+\.\d+)<.+?>(\d+\.\d+)<!s or die "Gagal memparsing kurs CHF\n";
#($chf_jual, $chf_beli) = ($1, $2);
print "USD jual=$usd_jual, beli=$usd_beli (Sumber: BCA, $waktu)\n";
