#!/usr/bin/perl

# 991125

$|++;
use lib '/home/steven/p/steven/valuehit/prog/pm/';
use Valuehit::Utils::Filedir;
use Fcntl;
use HTML::Entities;
*e = \&HTML::Entities::encode_entities;

my $catdb  = "/home/steven/tmp/cumi/kategori.db";
my $itemdb = "/home/steven/tmp/cumi/cumidata.db";
my $targetdir = "/home/steven/tmp/cumi/direk";

my %cat;
my %item;

sub baca {

open F, $catdb or die;
my @f;
while(<F>){
	@f=split /\|/, $_;
	$cat{$f[1]} = { id=>$f[0] };
}

open F, $itemdb or die;
while(<F>){
	@f=split /\|/, $_;
	$item{$f[0]} = { id=>$f[0],name=>$f[1],url=>$f[2],cat=>$f[4],desc=>$f[5] };
}

}

###

sub encode {
	my $it = shift;
	$it =~ s/([^A-Za-z0-9 ,\.\(\)\[\]\-_&'!\#])/sprintf("%%%02x",ord($1))/eg;
	".$it";
}

sub decode {
	my $it = shift;
	$it =~ s/^\.//;
	$it =~ s/%(..)/hex($1)/eg;
	$it;
}

sub encode_dir {
	local $_;
	$_=join '/', map {encode($_)} split /\//, $_[0];
	print $_;
	return $_;
}

sub decode_dir {
	return join '/', map {decode($_)} split /\//, $_[0];
}


sub buatdir {
	for my $p (sort keys %cat) {
		mkdir_p("$targetdir/".encode_dir($p)) or warn $Valuehit::Utils::Filedir::ERR;
		print "$p\n";
	}
}

sub buatitem {
	for my $p (keys %item) {
		$i=$item{$p};
		sysopen(F,"$targetdir/".encode_dir($i->{'cat'})."/".encode($i->{'name'}).".htm",O_WRONLY|O_CREAT|O_TRUNC)
		or die;
		print F "<HTML><TITLE>".e("$i->{'name'}: $i->{'desc'}")."</TITLE>\n";
		print F "<BIG><BIG>\n";
		print F "<P>name: ".e($i->{'name'})."</P>\n";
		print F "<P>cat: ".e($i->{'cat'})."</P>\n";
		print F "<P>desc: ".e($i->{'desc'})."</P>\n";
		print F "<P>url: <A HREF='$i->{url}'>".e($i->{'url'})."</A></P>\n";
		print F "</BIG></BIG>\n";
		print F "</HTML>\n";
		
#		print F "<FRAMESET ROWS=\"10%,*\">\n";
#		print F "
#		print F "</FRAMESET>\n";
		close F or die;
		print "$i->{cat} --> $i->{'name'}\n";
	}
}

baca();
buatdir();
buatitem();
