#!/bin/sh
rsync -e ssh -Pavz --del --delete-excluded --force --exclude '/.bzr' --exclude '*~' \
  ~/proj/mwn/masterkey mwnwhmcs@xenon:
rsync -e ssh -Pavz \
  ~/proj/spanel/lib/php/sh_functions.inc.php mwnwhmcs@xenon:

ssh mwnwhmcs@xenon masterkey/bin/masterkey-install \
  --branch prod \
  --source /home/mwnwhmcs/masterkey \
  --target /s/prod.whmcs.mwn.localdomain/www/ \
  --sh-functions-path /home/mwnwhmcs/sh_functions.inc.php \
  install \
  $*
