#!/bin/sh
rsync -e ssh -Pavz --del --delete-excluded --force --exclude '/.bzr' --exclude '*~' \
  ~/proj/mwn/masterkey mwnwhmcs@gold:

ssh mwnwhmcs@gold masterkey/bin/masterkey-install \
  --source /home/mwnwhmcs/masterkey \
  --target /s/prod.whmcs.mwn.localdomain/www/ \
  install \
  $*
