#!/bin/sh
~/proj/mwn/masterkey/bin/masterkey-install \
  --branch prod \
  --source ~/proj/mwn/masterkey \
  --target /s/testmkey.steven.builder.localdomain/www/ \
  --sh-functions-path /home/steven/proj/spanel/lib/php/sh_functions.inc.php \
  install \
  $*
