#!/usr/bin/perl

use Expect;
use Data::Dumper;
$micq='/usr/local/bin/micq';
$DELAY=5*60;

while(1) {

unlink '/home/steven/.micqrc';
undef $s;
$s = Expect->spawn($micq) or die;
#$s->debug(1);

$s->expect(5, "UIN: #");
print $s "0\r"; sleep 1;
$s->expect(2, "password : ") or do { sleep $DELAY; next;};
$randpass=join '', map { substr('abcdefghijklmnopqrstuvwxyz',rand(26),1) } 1..5;
print $s "$randpass\r"; sleep 1;
$s->expect(2, "verify: ") or next;
print $s "$randpass\r"; sleep 1;
$s->expect(30,"!") or next;
($num) = $s->exp_before() =~ /(\d{8})/;
#$s->expect(10, "want to use this) : ") or next;
print $s "0\r"; sleep 1;

open F, ">>/home/steven/bin/nomor";
print F scalar(localtime), ": $num = $randpass\n";
close F;
$s->hard_close();
sleep $DELAY;
#exit;
}
