#!/usr/bin/perl

use 5.010;
use strict;
use warnings;

use LWP::Simple;
use Mojo::DOM;

die "Usage: $0 <CPANID> ...\n" unless @ARGV;

for my $cpanid (@ARGV) {
    my $dom = Mojo::DOM->new(get "http://search.cpan.org/~".lc($cpanid)."/");
    my $trs = $dom->find('tr a[href*="/src/"]');
    printf "%s has %d distributions on CPAN\n", $cpanid, scalar(@$trs);
}
