#!/usr/bin/perl

# created: 2011-06-14

use 5.010;
use strict;
use warnings;

use LWP::Simple;
use Mojo::DOM;

die "Usage: $0 <CPANID> ...\n" unless @ARGV;

binmode STDOUT, ":utf8";

for my $cpanid (@ARGV) {
    my $dom = Mojo::DOM->new(get "http://search.cpan.org/~".lc($cpanid)."/");

    my $e = $dom->at("div[class=t1]");
    my $name = $e ? $e->text : undef;

    my $trs = $dom->find('tr a[href*="/src/"]');
    my $numdists = @$trs;

    printf "%s has %d distributions on CPAN\n",
        (defined($name) ? "$name ($cpanid)" : $cpanid), $numdists;
}
