#!/usr/bin/perl -w

use File::Slurp;
use strict;
use Cwd;

(-f "MANIFEST") or die "Can't find MANIFEST, maybe you're in the wrong directory?";

my @lines =
    sort {length($a)<=>length($b)}
    grep {m!^(lib/.+\.pm)$!}
    read_file("MANIFEST");

@lines or die "Can't find main module .pm file in MANIFEST";

my $version;
for my $fn (@lines) {
    chomp $fn;
    my $fc = read_file($fn);
    if ($fc =~ m#^our .VERSION = (['"])(.+)\1;#m) {
	$version = $2;
	last;
    }
}
die "Can't find VERSION line in any of these files: ".join(", ", @lines) unless $version;

$_ = getcwd();
s!.+/!!;

system "cd ../../_files && ".
    "rm -rf $_-$version $_-$version.tar.gz && ".
    "cp -a ../perl/$_ $_-$version && ".
    "tar cfz $_-$version.tar.gz $_-$version && ".
    "ls -l $_-$version.tar.gz";
