#!/bin/bash
perlrename -e '
if (!defined($COMMON_PREFIX)) {
  for ($i=0; $i<length($ARGV[0]); $i++) {
    last if grep { substr($_, $i, 1) ne substr($ARGV[0], $i, 1) } @ARGV[1..$#ARGV];
  }
  $COMMON_PREFIX = substr($ARGV[0], 0, $i);
}
s/^\Q$COMMON_PREFIX//g;
' "$@"
