#!/usr/bin/perl

use 5.010;
use strict;
use warnings;

use Lingua::FR::Numbers qw(number_to_fr);
use String::ShellQuote;

binmode STDOUT, ":utf8";

sub gen {
    my %args = @_;

    my $n   = $args{n}   // 5;
    my $min = $args{min} // 100;
    my $max = $args{max} // 1000000;
    my $fmt = length($max);

    for my $i (1..$n) {
        my $num   = int($min + ($max-$min+1)*rand());
        my $words = number_to_fr($num);
        printf "%-${fmt}d    = %s\n", $num, $words;
        system "espeak-mbrola 2>/dev/null --mv fr4 ".shell_quote($words);
        sleep 5;
    }
}

sleep 2;
gen();
