#!/bin/sh

ps ax | fgrep '[bcrypt' | grep -v grep | perl -slane'system "renice 2 $F[0]"'
ps ax | fgrep 'kcryptd' | grep -v grep | perl -slane'system "renice 2 $F[0]"'
ps ax | fgrep '[loop' | grep -v grep | perl -slane'system "renice 2 $F[0]"'
