#!/usr/bin/perl

open F, "JADS.pm" or die "Can't open JADS.pm: $!\n";
while (<F>) {
  if (/add_(?:error|warning)\s*\(\s*(\d+)/) {
    if ($nums{$1+0}++) {
      print "WARN: $1 is used more than once\n";
    }
  }
  if (/#\s*deprecated error codes?:\s*(.+)/) {
    my $s = $1;
    $depr{$1}++ while ($s =~ /(\d+)/g);
  }
}
#use Data::Dumper; print Dumper \%nums;
@nums = sort {$a <=> $b} keys %nums;
for ($nums[0] .. $nums[-1]) {
  next unless $_ >= 1;
  push @missing, $_ unless (exists($nums{$_}) || exists($depr{$_}));
}
print "WARN: Numbers don't start at 1, it starts at $nums[0]\n" if ($nums[0] != 1) && (!exists($depr{1}));
print "WARN: Some numbers are not used: ".(join " ", @missing)."\n" if @missing;
print "INFO: Next number to use is ".($nums[-1]+1)."\n";
