#!/usr/bin/perl

# 030412

die "Usage: $0 frames FILE\n" unless @ARGV >= 1;
$_ = shift @ARGV;
if (/^[+-]?\d+$/) {
	$frames = $_;
} else {
	die "FATAL: Invalid number of frames `$_'\n";
}

while (<>) {
	next unless /\S/;
	($frame1, $frame2, $text) = /\{(\d+)\}\{(\d+)\}(.*)/ or
		die "FATAL: Invalid entry in line $.: $_\n";
	printf "{%d}{%d}%s\n", $frame1+$frames, $frame2+$frames, $text;
}
