#!/usr/bin/perl

# 20040717 - bah, ntpd is useless for dialup (not-always-connected) machines

if (qx(/sbin/ifconfig) =~ /^ppp0/m) {
  $output = qx(/usr/sbin/ntptimeset -vuS1 -ddd -s 2>&1);
  if ($output !~ /^Time set to /m) {
    print "Can't set time. ntptimeset full output below:\n\n$output";
  }
}
