#!/bin/sh

SOURCE=/home/steven/proj/mwn/spanel-configs/servers

# note: -rlptD = -a minus -og (owner, group)

/c/sbin/spanel-multissh --rsync --user root --none --server server23 --server ciledug -- -rlptD -Pvz --del $SOURCE/* '[[USER]]@[[IP]]':/etc/spanel/servers/
/c/sbin/spanel-multissh --rsync --user root --has mwn --has dns --lack intranet       -- -rlptD -Pvz --del $SOURCE/* '[[USER]]@[[IP]]':/etc/spanel/servers/
