#!/usr/bin/perl

use strict;
use warnings;
use IO::Select;
use IO::Socket::UNIX;
use Getopt::Long;
use Log::Log4perl qw(:easy);

Log::Log4perl->easy_init($INFO);

if (@ARGV != 1) {
  die "Usage: $0 <path-to-socket>\n";
}

my $path = $ARGV[0];

my $sock = new IO::Socket::UNIX(Type=>SOCK_STREAM, Peer=>$path);
if (!$sock) { FATAL "Can't bind to socket $path: $@"; exit 1 }

my $sel = new IO::Select($sock);

while (1) {
    while (1) {
        my @ready = $sel->can_read(0.1);
        if (@ready) {
            my $reply = <$sock>;
            print $reply;
        } else {
            last;
        }
    }
    exit if !defined($sock); # sock is closed
    print "> ";
    my $line = <STDIN>;
    $sock->print($line);
}

