#!/usr/bin/perl

use strict;
use warnings;
use IO::Socket::UNIX;
use Getopt::Long;
use Log::Log4perl qw(:easy);

Log::Log4perl->easy_init($INFO);

if (@ARGV != 1) {
  die "Usage: $0 <path-to-socket>\n";
}

my $path = $ARGV[0];

my $sock = new IO::Socket::UNIX(Type=>SOCK_STREAM, Peer=>$path);
if (!$sock) { FATAL "Can't bind to socket $path: $@"; exit 1 }

print "Commands: s=send a line, r=read a line, q=quit\n\n";

for (;;) {
  print "command> ";
  my $cmd = <STDIN>; chomp($cmd);
  if ($cmd eq 'q') {
    exit;
  } elsif ($cmd eq 'r') {
    my $reply = <$sock>;
    print "recv> $reply";
  } elsif ($cmd eq 's') {
    print "send> ";
    my $line = <STDIN>;
    $sock->print($line);
  } else {
    ERROR "Invalid command";
  }
}

