#!/usr/bin/perl

# test hasil rpm ipdb, 020318

use Data::Dumper;

$|++;
$ipdb_path = "/usr/share/ipdb.perl";

die "Sorry, please run me as root\n" if $>;

print "load IPDB.pm: ";
eval { use IPDB; };
print $@ ? "FAIL ($@)\n" : "OK\n";

print "$ipdb_path: ";
print +(-r $ipdb_path) ? "OK\n" : "FAIL (can't read)\n";

print "load_inmem_ipdb: ";
eval { load_inmem_ipdb($ipdb_path); };
print $@ ? "FAIL ($@)\n" : "OK\n";

print "inmem_ipblock_of_stringip (1): ";
$ipblock = inmem_ipblock_of_stringip("202.158.1.100");
print +(ref($ipblock) eq 'HASH' && $ipblock->{countrycode} eq 'id') ? "OK\n" : "FAIL (${\( Dumper $ipblock )})\n";

