#!/usr/bin/perl -w

# XXX TODO: user-configurable first line indent, subsequent line
# indent, line after para

use strict;
use Text::Wrap;

$Text::Wrap::columns = 80;

while (<>) {
    print wrap('', '', $_);
    print "\n"; # 1 line after each para
}
