#!/usr/bin/perl

# kok gak berhasil ya?
#use Text::Unaccent;

for $orig (@ARGV) {
  for ($safe) {
    $_ = $orig;
    s/é|è/e/g;
  }

  next if $safe eq $orig;

  $counter = 0;
  while (1) {
    $target = $safe . ($counter ? ".$counter" : "");
    unless (-e $target) {
      print "$orig -> $target\n";
      rename $orig, $target;
      last;
    }
    $counter++;
  }
}
