#!/usr/bin/perl

# created: 2012-01-03

# tugas skrip ini adalah mengamati file audio/video baru yang terbentuk di
# cache opera, lalu langsung meng-hardlinknya ke subdirektori _ln.  ini bisa
# dipake utk file2x audio video yang langsung ngilang aja di cache dan gak
# bisa disave oleh skrip watch-move-av-files-in-opera-cache

use 5.010;
use strict;
#use warnings;
use Log::Any::App '$log';

use autodie;
use File::chdir;
use File::MimeInfo;

my %mem;

$CWD = "$ENV{HOME}/.opera/cache";

mkdir "_ln" unless -d "_ln";

while (1) {
    $log->trace("Listing ...");
    for my $f (`ls g*/*.tmp --sort=t -r 2>/dev/null`) {
        chomp $f;
        my $fname = $f; $fname =~ s!.+/!!;
        next if $mem{$f}++;
        next if -f "_ln/$fname";
        $log->trace("found new file $f");
        my $filetype = `file $f`;
        my $ext;
        if    ($filetype =~ /audio.+id3|mpeg.+layer iii/i) { $ext = "mp3" }
        elsif ($filetype =~ /macromedia flash/i) { $ext = "flv" }
        elsif ($filetype =~ /mpeg v4/i) { $ext = "mp4" }
        else {
            $log->trace("type unknown, skipped");
            next;
        }
        $log->trace("$f is $ext file");
        $log->info("Linking $f to _ln/$fname ...");
        link $f, "_ln/$fname";
    } # for $f

    sleep 3;
}
