#!/bin/sh

# last-updated: 2006-08-18: server42 gw pake sebagai pc karena motherboard
# abit av8 error (kode 0.4, gak ada di manual, dah gw telanjangi semua
# kecuali prosesor, tetep aja 0.4, gak bisa sampe ke kode FF). amd64 3000+,
# motherboard gigabyte k8vm something, ram 2GB, vga onboard, eth onboard

# created: 2003-08-13

if test `id -u` -ne 0; then echo "You must be root to do this"; exit 1; fi

PATH=/usr/sbin:/usr/bin:/sbin:/bin:/u/steven/private/bin
ISLINUX26=`uname -r | grep -q ^2.6; if [ $? == 0 ]; then echo 1; else echo 0; fi`
ISLINUX24=`uname -r | grep -q ^2.4; if [ $? == 0 ]; then echo 1; else echo 0; fi`

echo "+ Mounting partitions..."
mount_storage_media marie
mount_storage_media
/home/steven/bin/renice-encrypted-partion

echo "+ Cleaning up pperl files..."
rm -f ~/.pperl/*; # 2007-08-04

echo "+ Setting 192.168.0.101 as default gateway..."
while test `route -n | grep -q '192.168.0.\(101\|103\)'; echo $?` -eq 0; do
  route del default gw 192.168.0.101
  route del default gw 192.168.0.103
done
route add default gw 192.168.0.101
#iptables -F; iptables -t nat -F

echo "+ Setting DNS resolver ..."

#bind
# elektrik is used as forwarder
#perl -pi -e's#^(\s+)// forwarders#${1}forwarders#' /etc/bind/named.conf.options
#/etc/init.d/bind9 restart

#dnscache
# elektrik is consulted for some zones
for d in ciledug.com localdomain; do echo 192.168.0.101 > /etc/dnscache/root/servers/$d; done
/etc/init.d/dnscache restart


echo "+ Setting auto-shutdown for IDE & SATA drives..."
# 241=30', 242=60'
df | perl -slane 'system "hdparm -S 242 $1" if $F[0] =~ m#^(/dev/(hd\w|sd\w))\d# && !$done{$1}'

echo "+ Starting squid..."
if test `ps ax | grep -q [s]quid; echo $?` -ne 0; then
  /etc/init.d/squid start
fi

#echo "+ Making sure samba is not automatically started"
#/etc/init.d/samba stop

echo "+ touch /etc/server=builder+elektrindo"
rm -f /etc/server=builder+*
touch /etc/server=builder+elektrindo

#echo "+ Copying XF86Config*.elektrindo to XF86Config*..."
#rm -f /etc/X11/XF86Config-4
#cp -a /etc/X11/XF86Config-4.elektrindo /etc/X11/XF86Config-4
# 2006-01-06 - sekarang kan pake xorg.conf dong
XCONF=/u/steven/private/etc/xorg.conf.elektrindo
XFINALCONF=/etc/X11/xorg.conf
echo "+ Copying $XCONF to $XFINALCONF..."
rm -f "$XFINALCONF"
cp -a "$XCONF" "$XFINALCONF"

echo "+ Installing sound card driver..."
if [ "$ISLINUX26" == 1 ]; then modprobe via82cxxx_audio
else insmod via82cxxx_audio; fi

echo "+ Done."
