#!/bin/bash 

tunctl -t tap0 -u steven
chmod 666 /dev/net/tun 
brctl addbr br0 
brctl addif br0 eth0 
brctl addif br0 tap0 
ifconfig tap0 0.0.0.0 promisc up 
ifconfig eth0 0.0.0.0 promisc up 
ifconfig br0 192.168.0.103 netmask 255.255.255.0 broadcast 192.168.0.255
# route del defautl gw dulu?
route add -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.0.101 dev br0 
