#!/bin/sh

# last-updated: 2006-09-18
# created: 2003-08-13

if test `id -u` -ne 0; then echo "You must be root to do this"; exit 1; fi

PATH=/u/steven/private/bin:/usr/sbin:/usr/bin:/sbin:/bin
ISLINUX26=`uname -r | grep -q ^2.6; if [ $? == 0 ]; then echo 1; else echo 0; fi`
ISLINUX24=`uname -r | grep -q ^2.4; if [ $? == 0 ]; then echo 1; else echo 0; fi`

echo "+ Mounting partitions..."
mount_storage_media -i eddie
mount_storage_media
/home/steven/bin/renice-encrypted-partition

#echo "+ Cleaning up pperl files..."
#rm -f ~/.pperl/*; # 2007-08-04

echo "+ Setting up DNS resolver ..."

# bind
# elektrik is NOT used as forwarder
#perl -pi -e's#^(\s+)forwarders#$1// forwarders#' /etc/bind/named.conf.options
#/etc/init.d/bind9 restart

#dnscache
# elektrik is NOT consulted for some zones
for d in ciledug.com localdomain 168.192.in-addr.arpa; do rm -f /etc/dnscache/root/servers/$d; done
/etc/init.d/dnscache restart


echo "+ Deleting default gateway..."
while test `route -n | grep -q '192.168.0.\(1\|103\)'; echo $?` -eq 0; do
  route del default gw 192.168.0.1
  route del default gw 192.168.0.103
done

echo "+ Setting auto-shutdown for IDE & SATA drives..."
# 241=30', 242=60'
df | perl -slane 'system "hdparm -S 242 $1" if $F[0] =~ m#^(/dev/(hd\w|sd\w))\d# && !$done{$1}'

#echo "+ Starting squid..."
#if test `ps ax | grep -q [s]quid; echo $?` -ne 0; then
#  /etc/init.d/squid start
#fi

#echo "+ Starting samba..."
#/etc/init.d/samba start

#echo "+ Starting ssh ..."
#/etc/init.d/ssh start

echo "+ touch /etc/server=builder+home..."
rm -f /etc/server=builder+*
touch /etc/server=builder+home

#echo "+ Copying XF86Config*.home to XF86Config*..."
#rm -f /etc/X11/XF86Config-4
#cp -a /etc/X11/XF86Config-4.home /etc/X11/XF86Config-4
# 2006-01-06 - sekarang kan pake xorg dong
echo "+ Copying xorg.conf.home to xorg.conf..."
rm -f /etc/X11/xorg.conf
cp -a /u/steven/private/etc/xorg.conf.home /etc/X11/xorg.conf

echo "+ Fixing cdrom driver installation..."
# hanya lakukan (terutama hdparm) jika ada cdrom tercolok
# XXX gimana jika bukan tercolok di hdb?
# rmmod ide-scsi && modprobe ide-cd && hdparm -d1 -k1 /dev/hdb

# qmail biasanya fail to start, kenapa ya?
echo "+ Starting qmail..."
/etc/init.d/qmail start

echo "+ Done."
