#!/usr/bin/perl -Tw

$ENV{PATH} = "/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin";
delete @ENV{qw/IFS CDPATH ENV BASH_ENV/};
$<=$>; $(=$);

chdir "/etc/sysconfig/network-scripts";
unless ($ARGV[0] eq '-d') {
  system "./ifdown eth1";
  sleep 3;
  system "./ifup eth1";
}
system "/sbin/route del default gw 202.43.165.21";
system "add-iix-routes.sh 2>/dev/null";
