#!/bin/bash
echo "Mounting /.block ..."
losetup /dev/loop0 /.block  && cryptsetup create 0 /dev/loop0 && mount /dev/mapper/0 /mnt
echo "Mounting /.block2 ..."
losetup /dev/loop1 /.block2 && cryptsetup create 1 /dev/loop1 && mount /dev/mapper/1 /mnt2
