#!/usr/bin/perl

open F, "spec2sql" or die "Can't open spec2sql: $!\n";
while (<F>) {
  $nums{$1}++ if /spec_(?:error|warn|note)\s*\(\s*(\d+)\s*,/;
  if (/#\s*deprecated error codes?:\s*(.+)/) {
    my $s = $1;
    $depr{$1}++ while ($s =~ /(\d+)/g);
  }
}
@nums = sort {$a <=> $b} keys %nums;
for ($nums[0] .. $nums[-1]) {
  next unless $_ >= 1;
  push @missing, $_ unless (exists($nums{$_}) || exists($depr{$_}));
}
print "WARN: Numbers don't start at 1, it starts at $nums[0]\n" if ($nums[0] != 1) && (!exists($depr{1}));
print "WARN: Some numbers are not used: ".(join " ", @missing)."\n" if @missing;
print "INFO: Next number to use is ".($nums[-1]+1)."\n";
