#!/bin/sh

rsync -e ssh --delete -Pavz \
  --exclude '*.exe' \
  --exclude '*.swf' \
  --exclude '*~' \
  --exclude 'webmail/*' \
  --exclude 'templates/*' \
  --exclude 'images/banners/*' \
  --exclude 'bandung/menu.js' --exclude 'jakarta/menu.js' \
  /home/steven/sites/myesia.steven.builder.localdomain/www/ \
  myesiacom@myesia.com:/s/myesia.com/www/
