#!/bin/sh -x

# created: 2005-05-17
# last-updated: 2005-05-17

TARGET=root@flyer.localdomain
alias rsync1="rsync -e ssh -avz --delete --force"

# slk
rsync1 /e/u/slk/home/* $TARGET:/e/u/slk/home/

# v
rsync1 /e/u/v/home/{*,.opera,.mozilla*,.galeon} $TARGET:/e/u/v/home/

# steven
/home/steven/bin/sync-steven-to-flyer

unalias rsync1
