#!/usr/bin/perl -Tw

# last updated: 2005-08-18

use FindBin qw($Bin);
use lib "$Bin";
BEGIN { ($Bin) = $Bin =~ /(.+)/; require "$Bin/common.pl"; }

print <<_;

Skrip ini akan menghapus semua route nonlocal lalu setelah itu Anda dapat
mendial modem menggunakan wvdial. Gunakan dalam kondisi darurat yaitu jika
uplink DTP mati. Koneksi IIX dan internasional akan lambat karena
menggunakan dialup.

Tekan ENTER untuk lanjut atau Ctrl-C untuk keluar.

_

$_ = <STDIN> unless @ARGV;

clean_env();

turn_on_eth0();

delete_all_nonlocal_routes();

turn_off_all_tundevs();

#mysystem "wvdial cbn";
#mysystem "wvdial telkomnet";
print "+ Done. Silakan ketik 'wvdial cbn' atau 'wvdial telkomnet'. Sebelumnya pastikan modem telah terpasang di server.\n";
