#!/usr/bin/perl

use 5.010;
use strict;
use warnings;

use Cwd;

die "Please run me in repo root dir\n" unless (-d ".git");
my $cwd = getcwd;
my $repo_name = $cwd; $repo_name =~ s!.+/!!;
my $repo_name_lc = lc $repo_name;

my $output = `git config --get remote.gitorious.url`;
die "Remote URL already added\n" unless $?;

system "git", "remote", "add", "gitorious",
    "git\@gitorious.org:$repo_name_lc/$repo_name_lc.git";

