#!/bin/bash
NAME=shorganizer
SRCDIR=~
TARGETDIR=/tmp
TARGET="$TARGETDIR/$NAME-`date +'%Y%m%d'`.tar.pgp"

tar cf - "$SRCDIR/$NAME" | gpg --encrypt --sign --recipient steven - > "$TARGET"
ls -l "$TARGET"
