#!/bin/bash
DEST=""
a=/media/b92c91cb-7f29-4b36-9f31-90bab7db0583
if [[ -d "$a" ]]; then DEST="$a"
else
    a=/media/cruzer0
    if [[ -d "$a" ]]; then DEST="$a"
    else
        a=/media/cruzer
        if [[ -d "$a" ]]; then DEST="$a"; fi
    fi
fi

if [[ ! "$DEST" ]]; then echo "FATAL: Can't find backup media cruzer"; exit 1; fi

backup-repos --src=$HOME/repo --dest=$DEST/repo "$@"
