#!/bin/bash
DEST=""
a=/media/d7da0725-cc3e-4036-9be3-e774d2d01d87
if [[ -d "$a" ]]; then DEST="$a"
else
    a=/media/toshiba0
    if [[ -d "$a" ]]; then DEST="$a"
    else
        a=/media/toshiba
        if [[ -d "$a" ]]; then DEST="$a"; fi
    fi
fi

if [[ ! "$DEST" ]]; then echo "FATAL: Can't find backup media toshiba"; exit 1; fi

gitbunch backup "$@" $HOME/repos $DEST/repos
