#!/bin/bash
set -x

DEV=cruzer

mount /media/$DEV
success=0
if [[ $? == 0 ]]; then success=1; fi
if [[ $? == 32 && -d /media/$DEV && -d /media/$DEV/mnt ]]; then success=1; fi
if [[ ! $success ]]; then exit 1; fi

