#!/usr/bin/perl

# saat ini gw suka ada banyak harddisk. gw suka nyalain komputer sampe
# berhari2. gw juga suka masang various harddisk (yang isinya
# download-an) dan gak ngemount harddisk backup sampe berhari2. ini
# berarti data gw gak terbackup berhari2.
#
# gw mount harddisks di /media/NAMAMEDIA.
#
# at least utk data di home (encrypted partition), gw sekarang pasang
# /media/FOO/encrypted dan backup ke sana tiap hari menggunakan skrip.

my $NUM_HISTORIES = 7;

# ---

use warnings;
use strict;
use POSIX;

my $mount_o = `mount`;
$mount_o =~ m{ on (/media/[^/]+/encrypted)} or 
$mount_o =~ m{ on (/media/[^/ ]+) .+BestCrypt} or 
  die "No encrypted volume available under /media/*\n";

my $part = $1;
mkdir "$part/backup", 0700;
chdir "$part/backup" or die "Can't chdir to $part/backup: $!\n";

my $now = time;
my @st0 = stat(".current.timestamp");
my $timest0 = POSIX::strftime("%Y-%m-%d\@%H:%M:%S+00", gmtime($st0[9] || $now));

if (-d "current") {
  system "cp -la $part/backup/current $part/backup/hist.$timest0";
} else {
  mkdir "current", 0700;
}

system "nice -n19 rsync -av --del --delete-excluded".
  " --exclude swapfile".
  " --exclude '*~'".
  " --exclude '*/cache*' --exclude '*/Cache*'".
  " --exclude '*/Trash' --exclude '*/tmp'".
  " --exclude '*/spool/squid'".
  " --exclude '*/home/.thumbnails'".
  " /encrypted/ current/";

# only maintain a limited number of history backups
my @h = reverse sort (<hist.*>);
splice @h, 0, $NUM_HISTORIES;
for (@h) {
  print "Deleting old backup $part/backup/$_ ...";
  system "rm -rf $_";
}

system "touch .current.timestamp";
