#!/usr/bin/perl

# 2011-09-08: cara ini harusnya tidak ditempuh, karena membypass proses build.
# harusnya cara upload spanel itu dengan build lalu upload hasil build ke master
# repo, bukan dengan mengubah repo secara langsung. tapi ini sementara, karena
# repo spanel utama sedang broken.

use 5.010;
use strict;
use warnings;

#use Cwd;
use File::chdir;
use File::Slurp;
use String::ShellQuote;

my @HOSTS = ("spanel.info", "us.spanel.info");
my $USER  = "spsloki";

die "Usage: $0 <file> ...\n" unless @ARGV;

#my $cwd = getcwd();
unless ((-d ".git") && read_file(".git/description") =~ /spanel/i) {
    die "Not in Spanel repository top-level dir, please make sure .git ".
        "exists and .git/description contains 'spanel'\n";
}

# check all first
for my $f (@ARGV) {
    die "$f doesn't exist\n" unless (-e $f);
    die "$f not a file, currently only files are supported\n" unless (-f $f);
}

for my $f (@ARGV) {
    my $dir;
    if ($f =~ m!/!) { $dir = $f; $dir =~ s!(.+)/(.*)!$1! } else { $dir = "." }
    for my $h (@HOSTS) {
        my $cmd = "scp ".shell_quote($f)." $USER\@$h:public/spanel/releases/1.3-lenny/*/$dir/";
        print $cmd, "\n";
        system $cmd;
    }
}
