#!/bin/bash

echo "Deploying ..."
rsync --del -e ssh -avz $* \
  --exclude '*~' --exclude '.git' --exclude '/www' --exclude '/doc' \
  $HOME/repos/gudangapi/ \
  steven@xenon.localdomain:gudangapi/

echo "Deploying www ..."
rsync --del -e ssh -avz $* \
  --exclude '*~' --exclude '.git' \
  $HOME/repos/gudangapi/www/ \
  steven@xenon.localdomain:/s/gudangapi.com/www/

