#!/bin/sh

SRC=$HOME/repos/spanel-site
USER=spsloki
HOST1=spanel.info
HOST2=us.spanel.info
PATH_WWW=www
PATH_BIN=bin

for HOST in $HOST1 $HOST2; do
    echo "=> Deploying to $HOST ..."
    rsync -avz --del --exclude '*~' $SRC/www/{editions,install-spanel*,.htaccess,check-license,admin,pgp.txt} $USER@$HOST:$PATH_WWW/
    rsync -avz --del --exclude '*~' $SRC/lib/ $USER@$HOST:$PATH_WWW/lib/
    rsync -avz --del --exclude '*~' $SRC/bin/ $USER@$HOST:$PATH_BIN/
done
