#!/bin/sh

SRC=$HOME/repo/spanel
# default is 'spanel' in home directory
TARGET=spanel

echo "Updating distribution directory (~/spanel) on remote servers ..."
$SRC/sbin/spanel-multissh $@ --background --debug --nouse-ip --user root -- \
  'rsync::' -avz --del --force --delete-excluded --exclude '.svn' --exclude '.bzr' --exclude '.git' --exclude '*~' \
    $HOME/tmp/spanel/ '[[USER]]@[[IP_OR_HOSTNAME]]':$TARGET/ \
  'ssh::' spanel/sbin/spanel-install
  # XXX not yet: optional: run spanel-setup
