#!/bin/sh

SRC=$HOME/repos/spanel-site
USER=spsloki
HOST1=spanel.sloki.com
HOST2=us.spanel.sloki.com
PATH_WWW=www
PATH_BIN=bin

for HOST in $HOST1 $HOST2; do
    echo "=> Deploying to $HOST ..."
    rsync -avz --del --exclude '*~' \
        --exclude 'install-spanel' --exclude 'upgrade-spanel' \
        --exclude '/lib' \
        $SRC/www/ $USER@$HOST:$PATH_WWW/
    rsync -avz --del --exclude '*~' \
        $SRC/lib  $USER@$HOST:$PATH_WWW/
    rsync -avz --del --exclude '*~' \
        $SRC/bin/  $USER@$HOST:$PATH_BIN/
done
