#!/usr/bin/perl

use autodie;
use DateTime;

chdir "$ENV{HOME}/repo/shresearch/solidot";
my $d = DateTime->now;
system "mkdir -p ".$d->ymd("");
chdir $d->ymd("");
for (1..10) {
    system "wget -O ".$d->ymd("").".html http://solidot.org/index.pl?issue=".$d->ymd("");
    $d->subtract(days => 1);
}
