#!/usr/bin/perl

# generate =pkg lines from ~/repos, for Task::BeLike::SHARYANTO::Authored

use 5.010;
use strict;
use warnings;
use autodie;
use File::chdir;

my $repos = "$ENV{HOME}/repos";

$CWD = $repos;
for my $dir (grep {(-d) && /^perl-/} <*>) {
    my $mod = $dir;
    $mod =~ s/^perl-//;
    $mod =~ s/-/::/g;
    next if $mod =~ /^Task::/;
    next if (-f "$dir/.unreleased");
    print "=pkg $mod\n\n";
}
