#!/bin/bash
echo "Mounting /.block ..."
losetup /dev/loop0 /.block  && cryptsetup create 0 /dev/loop0 && mount /dev/mapper/0 /mnt
echo "Mounting /.block2 ..."
losetup /dev/loop1 /.block2 && cryptsetup create 1 /dev/loop1 && mount /dev/mapper/1 /mnt2

backup_device=/dev/sdb1
if [ -e "$backup_device" ]; then
    echo "Mounting /backup ..."
    mount "$backup_device" /backup
    echo "Mounting /backup/.block ..."
    losetup /dev/loop2 /backup/.block  && cryptsetup create 2 /dev/loop2 && mount /dev/mapper/2 /backup/mnt
    echo "Mounting /backup/.block2 ..."
    losetup /dev/loop3 /backup/.block2 && cryptsetup create 3 /dev/loop3 && mount /dev/mapper/3 /backup/mnt2
fi
