#!/usr/bin/perl -w

use Log::Log4perl qw(:easy);
use autodie;
use strict;

#Log::Log4perl->easy_init($TRACE);
Log::Log4perl->easy_init($INFO);

my $src = "$ENV{HOME}/repo";
my $dest = "$ENV{HOME}/he/repo";

if ($0 =~ /[2-]builder/) {
    $dest = "$ENV{HOME}/hb/repo";
} elsif ($0 =~ /[2-]eddie/) {
    $dest = "$ENV{HOME}/he/repo";
} elsif ($0 =~ /[2-]capuchin/) {
    $dest = "$ENV{HOME}/hc/repo";
}

if ($0 =~ /2home$/) {
    ($src, $dest) = ($dest, $src);
}

chdir $dest;
for my $repo (grep {-d} <*>) {
    INFO "Processing repo `$repo` ...";
    chdir $repo;
    my $output = `LANG=C git pull '$src'/$repo 2>&1`;
    my $exit = $? & 255;
    if ($exit == 0 && $output =~ /Already up-to-date/) {
        DEBUG "Repo `$repo` is up to date, nothing to do";
    } elsif ($exit == 0 && $output =~ /^Updating |^Merge made by recursive/m) {
        INFO "Repo `$repo` updated";
    } else {
        FATAL "Can't figure out result of 'git pull' for repo `$repo`: exit=$exit, output=$output";
        die;
    }
    DEBUG "Result of 'git pull' for repo `$repo`: exit=$exit, output=$output";
    chdir "..";
}

