#!/bin/bash

if test `id -u` -ne 0; then echo "You must be root to do this"; exit 1; fi

WHICH=`echo $0 | grep -q home; if [ $? = 0 ]; then echo home; else echo $0 | grep -q office; if [ $? = 0 ]; then echo office; else echo laptop; fi; fi`
#echo "WHICH=$WHICH"; exit

if [ $WHICH = "laptop" ]; then
  PRIMARY_MEDIA=niles
  IP=192.168.0.104
else
  PRIMARY_MEDIA=eddie
  IP=192.168.0.103
fi

if [[ $1 == "" || $1 == "network" || $1 == "net" ]]; then
  echo "+ Setting network ..."
  ifconfig eth0 $IP
  while test `route -n | grep -q '192.168.0.[1-9]'; echo $?` -eq 0; do
    route del default gw 192.168.0.1
    route del default gw $IP
  done
  route add default gw 192.168.0.1
  #iptables -F; iptables -t nat -F
fi

if [[ $1 == "" || $1 == "hdd" ]]; then
  echo "+ Setting auto-shutdown for IDE & SATA drives ..."
  # 241=30', 242=60'
  df | perl -slane 'system "hdparm -S 242 $1" if $F[0] =~ m#^(/dev/(hd\w|sd\w))\d# && !$done{$1}'
fi

#echo "+ Starting squid ..."
#if test `ps ax | grep -q [s]quid; echo $?` -ne 0; then
#  /etc/init.d/squid start
#fi

#echo "+ Making sure samba is not automatically started"
#/etc/init.d/samba stop

#echo "+ touch /etc/server=builder+$WHICH"
#rm -f /etc/server=builder+*
#touch /etc/server=builder+$WHICH

if [ $WHICH != laptop ]; then
  XCONF=/u/$USER/private/etc/xorg.conf.$WHICH
  XFINALCONF=/etc/X11/xorg.conf
  echo "+ Copying $XCONF to $XFINALCONF..."
  rm -f "$XFINALCONF"
  cp -a "$XCONF" "$XFINALCONF"
fi

#echo "+ Installing sound card driver..."
#if [ "$ISLINUX26" = 1 ]; then modprobe snd_via82xx
#else insmod snd_via82xx; fi

#/etc/init.d/cgiexecd start
#/etc/init.d/mysql start
#/etc/init.d/apache2 start

echo "+ Done."
