#!/bin/bash

if test `id -u` -ne 0; then echo "You must be root to do this"; exit 1; fi

WHICH=`echo $0 | grep -q home; if [ $? = 0 ]; then echo home; else echo office; fi`
#echo "WHICH=$WHICH"; exit
PRIMARY_MEDIA=eddie
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/u/steven/private/bin
ISLINUX26=`uname -r | grep -q ^2.6; if [ $? = 0 ]; then echo 1; else echo 0; fi`
#ISLINUX24=`uname -r | grep -q ^2.4; if [ $? = 0 ]; then echo 1; else echo 0; fi`

if [[ $1 == "" || $1 == "mount" ]]; then
  echo "+ Mounting partitions ..."
  mount_storage_media -i $PRIMARY_MEDIA
  mount_storage_media
  /home/steven/bin/renice-encrypted-partition
fi

if [[ $1 == "" || $1 == "network" || $1 == "net" ]]; then
  echo "+ Setting network ..."
  ifconfig eth0 192.168.0.103
  while test `route -n | grep -q '192.168.0.\(1\|103\)'; echo $?` -eq 0; do
    route del default gw 192.168.0.1
    route del default gw 192.168.0.103
  done
  route add default gw 192.168.0.1
  #iptables -F; iptables -t nat -F
fi

if [[ $1 == "" || $1 == "hdd" ]]; then
  echo "+ Setting auto-shutdown for IDE & SATA drives ..."
  # 241=30', 242=60'
  df | perl -slane 'system "hdparm -S 242 $1" if $F[0] =~ m#^(/dev/(hd\w|sd\w))\d# && !$done{$1}'
fi

#echo "+ Starting squid ..."
#if test `ps ax | grep -q [s]quid; echo $?` -ne 0; then
#  /etc/init.d/squid start
#fi

#echo "+ Making sure samba is not automatically started"
#/etc/init.d/samba stop

#echo "+ touch /etc/server=builder+$WHICH"
#rm -f /etc/server=builder+*
#touch /etc/server=builder+$WHICH

XCONF=/u/steven/private/etc/xorg.conf.$WHICH
XFINALCONF=/etc/X11/xorg.conf
echo "+ Copying $XCONF to $XFINALCONF..."
rm -f "$XFINALCONF"
cp -a "$XCONF" "$XFINALCONF"

#echo "+ Installing sound card driver..."
#if [ "$ISLINUX26" = 1 ]; then modprobe snd_via82xx
#else insmod snd_via82xx; fi

#/etc/init.d/cgiexecd start
#/etc/init.d/mysql start
#/etc/init.d/apache2 start

echo "+ Done."
