#!/usr/bin/perl

use POSIX qw(strftime);

BEGIN {
  $PROJ_DIR = "$ENV{HOME}/proj/spanel";
  $TARGET_DIR = "$ENV{HOME}/tmp";
}

# ---

use lib "$PROJ_DIR/lib/perl";
use Spanel;

chdir $PROJ_DIR or die "FATAL: Can't chdir to `$PROJ_DIR': $!\n";

my $timestamp = strftime "%Y%m%d", localtime;
my $targetn = "spanel-$Spanel::VERSION.$Spanel::REVISION";
my $targetp = "$TARGET_DIR/$targetn";

system qq{git archive -v --prefix=$targetn/ HEAD | gzip -c > $targetp.tar.gz};
system qq{ls -l $targetp.tar.gz};
