#!/bin/bash
sshfs -o idmap=user -o umask=022 steven@gold:/             /media/gold
sshfs -o idmap=user -o umask=022 steven@hosting:/          /media/bismuthb
sshfs -o idmap=user -o umask=022 s10010@23.masterweb.net:/ /media/server23
sshfs -o idmap=user -o umask=022 steven@xenon:/            /media/xenon
