#!/bin/bash

# bunuh koneksi sebelumnya
killall -9 ssh sshfs
fusermount -u /media/builder

sshfs s1@builder:/ /media/builder

# sucky eee's eth. di sekitar 11MB pasti putus dulu. tapi kalo udah
# gagal sekali, biasanya jadi sukses. jadi kita pancing dulu aja
# gagalnya sekali di sini. opera=18M
rsync -Pavz s1@builder:/home/s1/repo/notes /tmp/
rm -rf /tmp/notes
