#!/bin/bash

kill-sshfs-builder
sshfs -o idmap=user s1@builder:/ /media/builder

#while true; do
    # sucky eee's eth. di sekitar 11MB pasti putus dulu. tapi kalo udah
    # gagal sekali, biasanya jadi sukses. jadi kita pancing dulu aja
    # gagalnya sekali di sini. opera=18M
#    rsync -Pavz s1@builder:/home/s1/repo/spanel/share/installers/moodle* /tmp/
#    rm -rf /tmp/moodle*
#done
