#!/bin/bash
sshfs -o idmap=user steven@gold:/             /media/gold
sshfs -o idmap=user steven@hosting:/          /media/bismuthb
sshfs -o idmap=user s10010@23.masterweb.net:/ /media/server23
sshfs -o idmap=user steven@xenon:/            /media/xenon
