#!/bin/bash
arch=debian-squeeze-amd64
plarch=x86_64-linux-gnu-thread-multi
ssh=$sshspaneldev_build_squeeze_amd64
rsync -avz --exclude "/lib/perl5/$plarch" $ssh:perl5/ $HOME/proj/spanel/perl5/
rsync -avz $ssh:perl5/lib/perl5/$plarch $HOME/proj/spanel/arch/$arch/perl5/lib/perl5/
