#!/bin/bash

SRC=/media/eddie/archive/free_doc
DEST=/archive/free_doc

if test -d $SRC; then
    rsync -avz --del --force $SRC/ $DEST/
else
    echo "Source $SRC not exist (not mounted yet?)"
    exit 1
fi
