#!/bin/bash

echo "============== Note: Saat ini hanya mengupload squeeze ===================="

# upload spanel to spanel.sloki.com

SRCREPO=$HOME/proj/spanel13
SRC=$HOME/tmp/spanel13
USER=spsloki
HOST1=spanel.sloki.com
HOST2=us.spanel.sloki.com
PATH_RELEASES=/u/spsloki/public/spanel/releases/1.3-squeeze

set -x

echo "==> Creating distribution ..."
#$SRCREPO/devscripts/fast-sync-to-dist --dest=$SRC
rsync -az --del --force --delete-excluded --exclude /.git --exclude /.gitignore --exclude '*~' $SRCREPO/ $SRC/

#echo "==> Preparing and uploading installer/upgrader script ..."
#$SRCREPO/devscripts/prepare-installer-script >/tmp/install-spanel && perl -c /tmp/install-spanel; [[ $? == 0 ]] || exit 1
#$SRCREPO/devscripts/prepare-upgrader-script  >/tmp/upgrade-spanel && perl -c /tmp/upgrade-spanel; [[ $? == 0 ]] || exit 1
#for HOST in $HOST1 $HOST2; do
#    PATH_INSTALLER=/u/$USER/sites/$HOST/www
#    rsync -avz /tmp/{install,upgrade}-spanel $USER@$HOST:$PATH_INSTALLER/
#done

if [[ "$UPLOAD" == "0" ]]; then echo "Skipping upload"; exit; fi

echo "==> Uploading distribution ..."
for HOST in $HOST1 $HOST2; do
    LAST_RELEASE=`ssh $USER@$HOST ls $PATH_RELEASES | sort | tail -1`
    NEW_RELEASE=`date +'%Y%m%d%H%M%S'`
    ssh $USER@$HOST "cd $PATH_RELEASES && cp -la $LAST_RELEASE .$NEW_RELEASE.rsync"
    rsync -avz --del --force $SRC/ $USER@$HOST:$PATH_RELEASES/.$NEW_RELEASE.rsync/
    ssh $USER@$HOST "cd $PATH_RELEASES && mv     .$NEW_RELEASE.rsync  $NEW_RELEASE"
done

echo "==> Updating release GUIDs ..."
for HOST in $HOST1 $HOST2; do
    ssh root@$HOST "/u/$USER/home/bin/publish-spanel-releases"
done
